version: "3.0"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    env_file: .env
  web:
    build: .
    image: ma-performance
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    container_name: redis
    image: redis:5-alpine
    ports:
      - 6378:6379
    volumes:
      - data-performance-redis:/data
  sidekiq:
    container_name: sidekiq
    image: ma-performance
    volumes:
      - .:/myapp:rw
    depends_on:
      - redis
      - db
    command: /bin/sh -c "bundle exec sidekiq"
    env_file: .env
volumes:
  data-performance:
    driver: local
  data-performance-redis:
    driver: local
  performance-bundle:
    driver: local
